countries_and_capitals = {
    "Albania": "Tirana", 
    "Andorra": "Andorra la Vella",
    "Austria": "Vienna", 
    "Belarus": "Minsk", 
    "Belgium":"Brussels",
    "Bosnia and Herzegovina": "Sarajevo", 
    "Bulgaria": "Sofia",                 
    "Croatia": "Zagreb", 
    "Cyprus": "Nicosia", 
    "Czechia": "Prague", 
    "Denmark": "Copenhagen", 
    "Estonia": "Tallin", 
    "Finland": "Helsinki", 
    "France": "Paris", 
    "Germany": "Berlin", 
    "Greece": "Athens",
    "Hungary" : "Budapest", 
    "Iceland": "Reykjavik",
    "Ireland": "Dublin", 
    "Italy" : "Rome", 
    "Kosovo": "Pristina", 
    "Latvia": "Riga", 
    "Liechtenstein": "Vaduz",
    "Lithunia": "Vilnius", 
    "Luxembourg": "Luxembourg", 
    "Malta": "Valletta", 
    "Moldova": "Chisinau", 
    "Monaco": "Monaco", 
    "Montenegro": "Podgorica", 
    "Netherlands": "Amsterdam Haag", 
    "North Macedonia": "Skopje", 
    "Norway": "Oslo", 
    "Poland": "Warsaw", 
    "Portugal": "Lisbon", 
    "Romania": "Bucharest", 
    "Russia": "Moscow", 
    "San Marino": "San Marino", 
    "Serbia": "Belgrade", 
    "Slovakia": "Bratislava", 
    "Slovenia": "Ljubljana", 
    "Spain": "Madrid", 
    "Sweden": "Stockholm", 
    "Switzerland": "Bern", 
    "Ukraine": "Kiev", 
    "United Kingdom": "London"
}